#cloud-config
# vim: syntax=yaml

users:
  - default
  - name: openstack
    gecos: Direct login account
    primary_group: openstack
    groups: users, admin
#
# kris-at-occ: Update 'expiredate' to appropriate value
#
    expiredate: 2018-09-01
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
#
# kris-at-occ: passwd: The hash -- not the password itself -- of the password you want
#           to use for this user. You can generate a safe hash via:
#               mkpasswd --method=SHA-512 --rounds=4096
#           (the above command would create from stdin an SHA-512 password hash
#           with 4096 salt rounds)
#           You may need to instal 'whois' package to run mkpasswd
#
#           Please note: while the use of a hashed password is better than
#               plain text, the use of this feature is not ideal. Also,
#               using a high number of salting rounds will help, but it should
#               not be relied upon.
#
#               To highlight this risk, running John the Ripper against the
#               example hash above, with a readily available wordlist, revealed
#               the true password in 12 seconds on a i7-2620QM.
#
#               In other words, this feature is a potential security risk and is
#               provided for your convenience only. If you do not fully trust the
#               medium over which your cloud-config will be transmitted, then you
#               should use SSH authentication only.
#
    passwd: $6$rounds=4096$9aqHXgHRwyFPNCz3$1IR5TIIleTc3S.7UbF8MCmeDXThhz2fNr7YFerbW5ybuvzxlQezqiDh2lGFrV3VXMuOPxeC6.Q8ZJ1jOv97fE1

write_files:
  - content: |
         cat <<-EOF > /var/www/html/test.html
         <html>
         <body>
         <p>Proudly served by $(hostname)</p>
         </body>
         </html>
         EOF
    owner: root:root
    path: /tmp/start_me_up.sh
    permissions: '0700'

packages:
  - nginx

runcmd:
  - sh /tmp/start_me_up.sh
