#cloud-config
# vim: syntax=yaml

packages:
  - apache2
  - rpl
  - php
  - libapache2-mod-php
  - php-mysql
  - php-curl
  - php-gd
  - php-pear
  - php-imagick
  - php-imap
  - php-mcrypt
  - php-recode
  - php-tidy
  - php-xmlrpc
  - mariadb-client

write_files:
  - content: |
         hostname=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/hostname | cut -f 1 -d '.')
         localipv4=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/local-ipv4)
         subnet_address=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/local-ipv4 | cut -f 1-3 -d '.')
         echo "$localipv4 $hostname" >> /etc/hosts
         cd /var/www/html
         wget http://wordpress.org/latest.tar.gz
         tar xzvf latest.tar.gz
         cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
         rpl database_name_here wordpressdb /var/www/html/wordpress/wp-config.php
         rpl username_here wordpressuser /var/www/html/wordpress/wp-config.php
         rpl password_here openstack /var/www/html/wordpress/wp-config.php
         rpl localhost $subnet_address.250 /var/www/html/wordpress/wp-config.php
         sudo chown -R www-data:www-data /var/www/html/
         sudo chmod -R 755 /var/www/html/
         rm -rf /var/www/html/index.html
         a2enmod headers
         a2enmod rewrite
         systemctl restart apache2
    owner: root:root
    path: /tmp/start_me_up.sh
    permissions: '0700'
runcmd:
  - sh /tmp/start_me_up.sh
